#import "/template/lib.typ": *
#import "glossary.typ" : glossary

#show: hm-template.with(
  title: "HM Template",
  subtitle: [Advanced Typst Styling],
  doc_type: "Modularbeit",
  authors: authors("Peter Lustig", "Max Mustermann"),
  // set to "de" for german
  language: "en",
  // Table of content depth, set to none to disable
  toc-depth: 2,
  // displays the acronyms defined in the acronyms dictionary
  // remove to disable
  glossary: glossary,
  // Leave empty for none
  bibliography: bibliography("sources.bib"),
  // Remove to disable, absolute path required
  appendix: "/appendix.typ",
)

// Template usage chapter, remove before publishing
// DO NOT EDIT THIS FILE !
#include "template/template_usage.typ"
// Add your content below in /chapters/*

// Include all chapters
#include "/chapters/01_introduction.typ"
